# Generated by Django 4.1.7 on 2023-04-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='DBMS',
        ),
    ]
